### PR TITLE
Update v2 schemas to include “#/definitions/“ …

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
…as a $ref prefix so Phil’s parse works

### CODE REVIEW

**Review by Erin-Mounts — APPROVED** [review]
Looks good to me.

**Review by philerooski — CHANGES_REQUESTED** [review]
Thanks, this helps a lot. Some of the v1 schemas need to be updated too since they are used in archive-map.json. Can you apply the same changes to the following schemas?

- schemas/v1/TaskResultObject.json
- schemas/v1/MotionRecord.json
- schemas/v1/TappingResultObject.json
- schemas/v1/WeatherResult.json
- schemas/v1/AudioLevelRecord.json

Those last two schemas (`schemas/v1/WeatherResult.json` and `schemas/v1/AudioLevelRecord.json`) only appear in `.["apps"]["anyOf"]`, so perhaps the fix is to update archive-map.json in that section to the v2 schemas. But I'm also noticing something weird with the iOS and Android build numbers there. Those schemas apply to build 0 of iOS and Android, but there is no build 0 for either.

**Comment by syoung-smallwisdom** [comment]
@philerooski 

I've updated the schema mappings where applicable. There are still a few references to v1 schemas b/c those are related to older assessments that have not been validated against the v2 schemas.

WRT "taskResult.json" - that file is marked as deprecated and was only ever included on iOS. Same with "answers.json" and "info.json" (as far as I know - @nategbrown9 is this correct?) It is included in the archives b/c Northwestern is still doing internal testing on iOS using those files which are required by Exporter 2.0 and Bridge 1.0

WRT build numbers, I am not sure I understand what you are referring to.  If you mean this bit:
```
      "appId": "mobile-toolbox",
      "iOS": 0,
      "android" : 0,
```
That references the Bridge revision (ie. build) number for those apps. iOS is currently on build 78, for example. The number here indicates the *minimum* build to which this mapping applies.

**Review by philerooski — APPROVED** [review]
The only v1 schema references are for an assessment (finger-tapping) which is not used in MTB, so it won't cause me any issues that those internal $ref's haven't been changed to JSON Pointers.

> That references the Bridge revision (ie. build) number for those apps. iOS is currently on build 78, for example. The number here indicates the minimum build to which this mapping applies.

That makes sense.

**Pull request merged**
